name = "Yume"
license = "GPL-3.0"
licenselink = "https://github.com/nrechn/yume/blob/master/LICENSE"
description = "A minimalistic blog theme."
homepage = "https://github.com/nrechn/yume"
tags = ["blog", "minimalist"]
features = ["disqus", "code highlighting", "google analytics", "twitter card", "toolbar color"]
min_version = 0.16

[author]
    name = "nrechn"
    homepage = "https://nrechn.de"
